CREATE TABLE "books" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "isbn" varchar(17) UNIQUE NOT NULL,
  "publication_year" smallint,
  CONSTRAINT "chk_pub_year" CHECK (publication_year BETWEEN 1000 AND 2100)
);

CREATE TABLE "book_genre" (
  "book_id" int NOT NULL,
  "ganre_id" int NOT NULL,
  PRIMARY KEY ("book_id", "ganre_id")
);

CREATE TABLE "genre" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "authors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL
);

CREATE TABLE "book_authors" (
  "book_id" int,
  "author_id" int,
  PRIMARY KEY ("book_id", "author_id")
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(40) UNIQUE NOT NULL
);

CREATE TABLE "book_categories" (
  "book_id" int,
  "category_id" int,
  PRIMARY KEY ("book_id", "category_id")
);

CREATE TABLE "members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "login" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(128) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "address" varchar(150) NOT NULL
);

CREATE TABLE "copy_statuses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "book_copies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" int NOT NULL,
  "barcode" varchar(30) UNIQUE NOT NULL,
  "copy_status_id" int NOT NULL
);

CREATE TABLE "borrowing_statuses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "borrowings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "borrowing_date" timestamp NOT NULL DEFAULT 'now()',
  "status_id" int NOT NULL,
);

CREATE TABLE "borrowing_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "borrowing_id" int NOT NULL,
  "book_copy_id" int NOT NULL,
  "return_date" timestamp,
  "due_date" timestamp NOT NULL,
);

CREATE TABLE "reservation_statuses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "reservations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "reservation_date" timestamp NOT NULL DEFAULT 'now()',
  "status_id" int NOT NULL
);

CREATE TABLE "reservation_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" int NOT NULL,
  "book_id" int NOT NULL,
  "book_copy_id" int
);

CREATE TABLE "book_reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "book_id" int NOT NULL,
  "review_text" text,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "rate" smallint NOT NULL,
  CONSTRAINT "chk_rate" CHECK (rate BETWEEN 1 AND 5)
);

CREATE UNIQUE INDEX "uq_borrowing_copy" ON "borrowing_items" ("borrowing_id", "book_copy_id");

CREATE INDEX "idx_res_items_res_book" ON "reservation_items" ("reservation_id", "book_id");

CREATE UNIQUE INDEX "uq_one_review_per_book" ON "book_reviews" ("member_id", "book_id");

ALTER TABLE "book_genre" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_authors" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_authors" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_categories" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_copies" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_copies" ADD FOREIGN KEY ("copy_status_id") REFERENCES "copy_statuses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "borrowings" ADD FOREIGN KEY ("member_id") REFERENCES "members" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "borrowings" ADD FOREIGN KEY ("status_id") REFERENCES "borrowing_statuses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "borrowing_items" ADD FOREIGN KEY ("borrowing_id") REFERENCES "borrowings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "borrowing_items" ADD FOREIGN KEY ("book_copy_id") REFERENCES "book_copies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("member_id") REFERENCES "members" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("status_id") REFERENCES "reservation_statuses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservation_items" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservation_items" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservation_items" ADD FOREIGN KEY ("book_copy_id") REFERENCES "book_copies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_reviews" ADD FOREIGN KEY ("member_id") REFERENCES "members" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "book_reviews" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id") DEFERRABLE INITIALLY IMMEDIATE;

INSERT INTO "copy_statuses" ("name") VALUES ('available'), ('borrowed'), ('reserved'), ('lost');
INSERT INTO "borrowing_statuses" ("name") VALUES ('active'), ('returned'), ('overdue');
INSERT INTO "reservation_statuses" ("name") VALUES ('pending'), ('fulfilled'), ('cancelled');

CREATE INDEX "idx_book_genre_genre_id"        ON "book_genre" ("genre_id");
CREATE INDEX "idx_book_authors_author_id"     ON "book_authors" ("author_id");
CREATE INDEX "idx_book_categories_cat_id"     ON "book_categories" ("category_id");
CREATE INDEX "idx_book_copies_book_id"        ON "book_copies" ("book_id");
CREATE INDEX "idx_book_copies_status_id"      ON "book_copies" ("copy_status_id");
CREATE INDEX "idx_borrowings_member_id"       ON "borrowings" ("member_id");
CREATE INDEX "idx_borrowings_status_id"       ON "borrowings" ("status_id");
CREATE INDEX "idx_borrowing_items_copy_id"    ON "borrowing_items" ("book_copy_id");
CREATE INDEX "idx_reservations_member_id"     ON "reservations" ("member_id");
CREATE INDEX "idx_reservations_status_id"     ON "reservations" ("status_id");
CREATE INDEX "idx_reservation_items_book_id"  ON "reservation_items" ("book_id");
CREATE INDEX "idx_reservation_items_copy_id"  ON "reservation_items" ("book_copy_id");
CREATE INDEX "idx_book_reviews_book_id"       ON "book_reviews" ("book_id");
