CREATE TABLE "books" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "isbn" varchar(17) UNIQUE NOT NULL,
  "publication_year" smallint,
  CONSTRAINT "chk_pub_year" CHECK (publication_year BETWEEN 1000 AND 2100)
);

CREATE TABLE "book_genre" (
  "book_id" int NOT NULL,
  "genre_id" int NOT NULL,
  PRIMARY KEY ("book_id", "genre_id")
);

CREATE TABLE "genre" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "authors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL
);

CREATE TABLE "book_authors" (
  "book_id" int,
  "author_id" int,
  PRIMARY KEY ("book_id", "author_id")
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(40) UNIQUE NOT NULL
);

CREATE TABLE "book_categories" (
  "book_id" int,
  "category_id" int,
  PRIMARY KEY ("book_id", "category_id")
);
