CREATE TABLE "books" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "isbn" varchar(17) UNIQUE NOT NULL,
  "publication_year" smallint,
  CONSTRAINT "chk_pub_year" CHECK (publication_year BETWEEN 1000 AND 2100)
);

CREATE TABLE "book_genre" (
  "book_id" int NOT NULL,
  "genre_id" int NOT NULL,
  PRIMARY KEY ("book_id", "genre_id")
);

CREATE TABLE "genre" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "authors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL
);

CREATE TABLE "book_authors" (
  "book_id" int,
  "author_id" int,
  PRIMARY KEY ("book_id", "author_id")
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(40) UNIQUE NOT NULL
);

CREATE TABLE "book_categories" (
  "book_id" int,
  "category_id" int,
  PRIMARY KEY ("book_id", "category_id")
);


CREATE TABLE "members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "login" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(128) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "address" varchar(150) NOT NULL
);

CREATE TABLE "copy_statuses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "book_copies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" int NOT NULL,
  "barcode" varchar(30) UNIQUE NOT NULL,
  "copy_status_id" int NOT NULL
);

CREATE TABLE "borrowing_statuses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "borrowings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "borrowing_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "status_id" int NOT NULL
);

CREATE TABLE "borrowing_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "borrowing_id" int NOT NULL,
  "book_copy_id" int NOT NULL,
  "return_date" timestamp,
  "due_date" timestamp NOT NULL
);

CREATE TABLE "reservation_statuses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "reservations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "reservation_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "status_id" int NOT NULL
);

CREATE TABLE "reservation_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" int NOT NULL,
  "book_id" int NOT NULL,
  "book_copy_id" int
);

CREATE TABLE "book_reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "book_id" int NOT NULL,
  "review_text" text,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "rate" smallint NOT NULL,
  CONSTRAINT "chk_rate" CHECK (rate BETWEEN 1 AND 5)
);
