CREATE TABLE "book" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "isbn" varchar(17) UNIQUE NOT NULL,
  "publication_year" smallint,
  CONSTRAINT "chk_pub_year" CHECK (publication_year BETWEEN 1000 AND 2100)
);

CREATE TABLE "genre" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "book_genre" (
  "book_id" int NOT NULL,
  "genre_id" int NOT NULL,
  PRIMARY KEY ("book_id", "genre_id")
);

CREATE TABLE "author" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL
);

CREATE TABLE "book_author" (
  "book_id" int,
  "author_id" int,
  PRIMARY KEY ("book_id", "author_id")
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(40) UNIQUE NOT NULL
);

CREATE TABLE "book_category" (
  "book_id" int,
  "category_id" int,
  PRIMARY KEY ("book_id", "category_id")
);

CREATE TABLE "member" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "login" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(128) NOT NULL,
  "phone" varchar(30) NOT NULL, -- Збільшено розмір
  "address" varchar(150) NOT NULL
);

CREATE TABLE "copy_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "book_copy" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" int NOT NULL,
  "barcode" varchar(30) UNIQUE NOT NULL,
  "copy_status_id" int NOT NULL
);

CREATE TABLE "borrowing_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "borrowing" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "borrowing_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Замінено на стандарт SQL
  "status_id" int NOT NULL
);

CREATE TABLE "borrowing_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "borrowing_id" int NOT NULL,
  "book_copy_id" int NOT NULL,
  "return_date" timestamp,
  "due_date" timestamp NOT NULL
);

CREATE TABLE "reservation_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "reservation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "reservation_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Замінено на стандарт SQL
  "status_id" int NOT NULL
);

CREATE TABLE "reservation_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" int NOT NULL,
  "book_id" int NOT NULL,
  "book_copy_id" int
);

CREATE TABLE "book_review" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "book_id" int NOT NULL,
  "review_text" text,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Замінено на стандарт SQL
  "rate" smallint NOT NULL,
  CONSTRAINT "chk_rate" CHECK (rate BETWEEN 1 AND 5)
);

-- Індекси та обмеження унікальності
CREATE UNIQUE INDEX "uq_borrowing_copy" ON "borrowing_item" ("borrowing_id", "book_copy_id");
CREATE INDEX "idx_res_items_res_book" ON "reservation_item" ("reservation_id", "book_id");
CREATE UNIQUE INDEX "uq_one_review_per_book" ON "book_review" ("member_id", "book_id");

-- Зовнішні ключі
ALTER TABLE "book_genre" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "book_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "book_author" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "book_author" ADD FOREIGN KEY ("author_id") REFERENCES "author" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "book_category" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "book_category" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "book_copy" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "book_copy" ADD FOREIGN KEY ("copy_status_id") REFERENCES "copy_status" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "borrowing" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "borrowing" ADD FOREIGN KEY ("status_id") REFERENCES "borrowing_status" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "borrowing_item" ADD FOREIGN KEY ("borrowing_id") REFERENCES "borrowing" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "borrowing_item" ADD FOREIGN KEY ("book_copy_id") REFERENCES "book_copy" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reservation" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reservation" ADD FOREIGN KEY ("status_id") REFERENCES "reservation_status" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reservation_item" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservation" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reservation_item" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reservation_item" ADD FOREIGN KEY ("book_copy_id") REFERENCES "book_copy" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "book_review" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "book_review" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- Наповнення довідників
INSERT INTO "copy_status" ("name") VALUES ('available'), ('borrowed'), ('reserved'), ('lost');
INSERT INTO "borrowing_status" ("name") VALUES ('active'), ('returned'), ('overdue');
INSERT INTO "reservation_status" ("name") VALUES ('pending'), ('fulfilled'), ('cancelled');

-- Додаткові індекси для перформансу
CREATE INDEX "idx_book_genre_genre_id"        ON "book_genre" ("genre_id");
CREATE INDEX "idx_book_authors_author_id"     ON "book_author" ("author_id");
CREATE INDEX "idx_book_categories_cat_id"     ON "book_category" ("category_id");
CREATE INDEX "idx_book_copies_book_id"        ON "book_copy" ("book_id");
CREATE INDEX "idx_book_copies_status_id"      ON "book_copy" ("copy_status_id");
CREATE INDEX "idx_borrowings_member_id"       ON "borrowing" ("member_id");
CREATE INDEX "idx_borrowings_status_id"       ON "borrowing" ("status_id");
CREATE INDEX "idx_borrowing_items_copy_id"    ON "borrowing_item" ("book_copy_id");
CREATE INDEX "idx_reservations_member_id"     ON "reservation" ("member_id");
CREATE INDEX "idx_reservations_status_id"     ON "reservation" ("status_id");
CREATE INDEX "idx_reservation_items_book_id"  ON "reservation_item" ("book_id");
CREATE INDEX "idx_reservation_items_copy_id"  ON "reservation_item" ("book_copy_id");
CREATE INDEX "idx_book_reviews_book_id"       ON "book_review" ("book_id");
